 新增薅羊毛任务通知

jd-base脚本成功添加新的定时任务：

jd_bean_change
jd_bean_home
jd_bean_sign
jd_blueCoin
jd_bookshop
jd_car
jd_car_exchange
jd_cash
jd_club_lottery
jd_coupon
jd_crazy_joy
jd_daily_egg
jd_dreamFactory
jd_family
jd_festival
jd_fruit
jd_get_share_code
jd_immortal
jd_immortal_answer
jd_jdfactory
jd_jdzz
jd_joy
jd_joy_feedPets
jd_joy_reward
jd_joy_run
jd_joy_steal
jd_jxnc
jd_kd
jd_live
jd_lotteryMachine
jd_mh
jd_moneyTree
jd_ms
jd_necklace
jd_nh
jd_nian
jd_nianCollect
jd_nian_ar
jd_nian_sign
jd_nian_wechat
jd_pet
jd_pigPet
jd_plantBean
jd_rankingList
jd_redPacket
jd_sgmh
jd_shop
jd_small_home
jd_speed
jd_superMarket
jd_super_box
jd_syj
jd_unbind
jd_unsubscribe
jd_xg
jx_sign
