name: Mirror the Github repos to Gitee
on:
   workflow_dispatch:
   watch:
    types: started
    push:
    branches: [ master ]
   schedule:
    - cron: '1 0,7,15 * * *'
jobs:
  run:
    name: Sync-GitHub-to-Gitee
    runs-on: ubuntu-latest
    steps:
    - name: Mirror the Github repos to Gitee.
      uses: Yikun/hub-mirror-action@v0.10
      with:
        src: github/lxk0301
        dst: gitee/wudongdefeng
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.PAT }}
        static_list: "jd_scripts"
        account_type: user
        force_update: true
